### ISSUE TITLE
Control of layout, locking and unlocking nodes

### ISSUE THREAD

**Issue by uscholdm** [eddie-thomas/rdf-scribe#3]
- It was surprising that after moving around the nodes to look just so, without warning, all that work was thrown away when going to a different slide and then back again. Have a popup that asks whether to save the position changes before leaving a slide.
  - Make it possible at a glance to see which nodes are currently locked, Maybe have a button that says 'show locked nodes' or better, 'show nodes that have been moved but are not locked'. I.e. nodes whose positioning information is at risk of being lost.

**Comment by eddie-thomas** [comment]
This has been addressed as of November 4th, 2023.

Nodes are, by default, "locked" in place.

You may now freely move nodes around with the expectation that:
- All nodes can still be re-positioned by a specific algorithm (DAG, COLA, Random, etc.)
- All nodes will be, by default, "locked" in place
- All nodes will be able to move via `drag` interaction, after which they will resume their original state of being "locked" in place
