### ISSUE TITLE
Save out edited turtle to a file

### ISSUE THREAD

**Issue by uscholdm** [eddie-thomas/rdf-scribe#9]
Ability to save to a file any edits to the turtle in the left pane

**Comment by eddie-thomas** [comment]
@uscholdm This particular feature request cannot be accomplished with the current set up. This would involve some server code to be able to change files live (e.g. Node.JS, GoLang, Flask(python), etc.).

This is why I built the web app with an in-app editor.

**Comment by uscholdm** [comment]
OK - that makes sense.
